### ISSUE TITLE
Are you building a plugin?

### ISSUE THREAD

**Issue by galzil** [danlapid/homebridge-tami4edge#1]
I'll be happy with just getting the Boil water button.
There's a [Smarthings Smart app](https://github.com/leo212/tami4edge-smarthings-unofficial) that I saw

**Comment by danlapid** [comment]
Yeah that’s actually exactly what I’m doing
Pretty much same things as what you sent though it would be a great reference
I’m almost finished but uni exam period started so I pushed this aside
Will probably finish it a count end of February/march

**Comment by galzil** [comment]
Thanks for that :-)

**Comment by danlapid** [comment]
So, it works and its published, problem is, I have no idea how you can get the refresh token needed.
I ran the mobile app on my computer and routed it through a proxy to intercept the token exchange.
The solution in the smarthings plugin is outdated and doesn't work anymore and cracking reCaptchaV3 is out of scope so.. dunno.
If you feel like running the app through a proxy or you have an idea on how to get the token some other way I'd love to know.

**Comment by galzil** [comment]
Nice work!
I've installed this [plugin ](https://github.com/nitaybz/homebridge-tami4#readme) last month, It's a long install but it works great
